"""Convection-Diffusion (thermal) problemtype — Python port of the built-in.

A faithful port of src/problemtype/builtins/convectionDiffusion.ts, kept as a
worked example of the Python authoring API (parity-tested against the
TypeScript original). The declaration is generated from the TypeScript original
by scripts/problemtype-to-python.mjs; only the hook is hand-written. Shows a
law-less material: the empty ``material_law`` name omits the
``constitutive_law`` block, so the thermal materials file carries variables
only.
"""

from kratos_problemtype import (define_problemtype, section, field, field_group,
                                condition, material_law)

NAME = "Convection-Diffusion (Python example)"


def _resolve(node, assignment, ctx):
    """Replaces the $path / $root / $field:<id> placeholders of a template."""
    if isinstance(node, str):
        if node == "$path":
            return ctx["model_part_name"] + "." + assignment["smpPath"].replace("/", ".")
        if node == "$root":
            return ctx["model_part_name"]
        if node.startswith("$field:"):
            return assignment["values"].get(node[len("$field:"):])
        return node
    if isinstance(node, list):
        return [_resolve(item, assignment, ctx) for item in node]
    if isinstance(node, dict):
        return {key: _resolve(item, assignment, ctx) for key, item in node.items()}
    return node


def _broadcast_constrained(cond, assignment, ctx):
    """The single "Fixed" checkbox of an Assign*VariableProcess on nodes becomes
    Kratos' per-component ``constrained: [b, b, b]`` (None for any other condition)."""
    template = cond["processTemplate"]
    if template.get("python_module") != "assign_vector_variable_process":
        return None
    process = _resolve(template, assignment, ctx)
    fixed = assignment["values"].get("constrained", True)
    fixed = fixed if isinstance(fixed, bool) else True
    value = assignment["values"].get("value", [0, 0, 0])
    process["Parameters"]["constrained"] = [fixed, fixed, fixed]
    process["Parameters"]["value"] = value if isinstance(value, list) else [0, 0, 0]
    return process


def _linear_solver(values):
    """``linear_solver_settings`` for the chosen solver (None for Automatic)."""
    solver = values["linearSolver"]
    if solver in ("cg", "bicgstab"):
        return {
            "solver_type": solver,
            "max_iteration": values["linearMaxIteration"],
            "tolerance": values["linearTolerance"],
            "preconditioner_type": values["preconditioner"],
            "scaling": False,
        }
    if solver != "automatic":
        return {"solver_type": solver}
    return None


def solver_settings(values, ctx):
    non_linear = values["analysisType"] == "non_linear"
    settings = {
        "solver_type": values["solverType"],
        "analysis_type": "non_linear" if non_linear else "linear",
        "model_part_name": ctx["model_part_name"],
        "domain_size": ctx["domain_size"],
        "model_import_settings": {"input_type": "mdpa", "input_filename": ctx["mdpa_stem"]},
        "material_import_settings": {"materials_filename": ctx["materials_file_name"]},
        "echo_level": values["echoLevel"],
        # Derived from the assignments, like the fluid solver's skin_parts.
        "problem_domain_sub_model_part_list": ctx["parts_model_parts"],
        "processes_sub_model_part_list": ctx["skin_model_parts"],
        "time_stepping": {"time_step": values["timeStep"]},
    }
    if values["computeReactions"]:
        settings["compute_reactions"] = True
    if non_linear:
        criterion = values["convergenceCriterion"]
        settings["convergence_criterion"] = criterion
        if criterion != "displacement_criterion":
            settings["residual_relative_tolerance"] = values["residualRelTol"]
            settings["residual_absolute_tolerance"] = values["residualAbsTol"]
        if criterion != "residual_criterion":
            settings["solution_relative_tolerance"] = values["temperatureRelTol"]
            settings["solution_absolute_tolerance"] = values["temperatureAbsTol"]
        settings["max_iteration"] = values["maxIteration"]
        settings["line_search"] = values["lineSearch"]
    linear = _linear_solver(values)
    if linear:
        settings["linear_solver_settings"] = linear
    if values["solverType"] == "stationary":
        settings["element_replace_settings"] = {"element_name": "LaplacianElement", "condition_name": "ThermalFace"}
    return settings


# --- declaration of "convectionDiffusion" generated by scripts/problemtype-to-python.mjs ---
SECTION_0 = section("problem", "Problem data",
    field("solverType", "Analysis", "enum", default="transient", options=[{"value": "transient", "label": "Transient"}, {"value": "stationary", "label": "Stationary"}], group="analysis"),
    field("analysisType", "Linearity", "enum", default="linear", options=[{"value": "linear", "label": "Linear"}, {"value": "non_linear", "label": "Non-linear"}], group="analysis"),
    field("startTime", "Start time", "number", default=0, unit="s", group="time"),
    field("timeStep", "Time step", "number", default=0.1, unit="s", group="time", min=0),
    field("endTime", "End time", "number", default=1, unit="s", group="time"),
    field("convergenceCriterion", "Convergence criterion", "enum", default="residual_criterion", options=[{"value": "residual_criterion", "label": "Residual"}, {"value": "displacement_criterion", "label": "Temperature"}, {"value": "and_criterion", "label": "Residual and temperature"}, {"value": "or_criterion", "label": "Residual or temperature"}], visible_when={"field": "analysisType", "equals": "non_linear"}, group="nonlinear"),
    field("residualRelTol", "Residual rel. tol.", "number", default=0.00001, visible_when=[{"field": "analysisType", "equals": "non_linear"}, {"field": "convergenceCriterion", "one_of": ["residual_criterion", "and_criterion", "or_criterion"]}], group="nonlinear", min=0),
    field("residualAbsTol", "Residual abs. tol.", "number", default=1e-7, visible_when=[{"field": "analysisType", "equals": "non_linear"}, {"field": "convergenceCriterion", "one_of": ["residual_criterion", "and_criterion", "or_criterion"]}], group="nonlinear", min=0),
    field("temperatureRelTol", "Temperature rel. tol.", "number", default=0.00001, visible_when=[{"field": "analysisType", "equals": "non_linear"}, {"field": "convergenceCriterion", "one_of": ["displacement_criterion", "and_criterion", "or_criterion"]}], group="nonlinear", min=0),
    field("temperatureAbsTol", "Temperature abs. tol.", "number", default=1e-7, visible_when=[{"field": "analysisType", "equals": "non_linear"}, {"field": "convergenceCriterion", "one_of": ["displacement_criterion", "and_criterion", "or_criterion"]}], group="nonlinear", min=0),
    field("maxIteration", "Max iterations", "int", default=10, visible_when={"field": "analysisType", "equals": "non_linear"}, group="nonlinear", min=1),
    field("lineSearch", "Line search", "bool", default=False, visible_when={"field": "analysisType", "equals": "non_linear"}, group="nonlinear"),
    field("linearSolver", "Solver", "enum", default="automatic", options=[{"value": "automatic", "label": "Automatic"}, {"value": "LinearSolversApplication.sparse_lu", "label": "Sparse LU"}, {"value": "cg", "label": "Conjugate gradients"}, {"value": "bicgstab", "label": "BiCGStab"}], help="Automatic lets Kratos pick the default solver of the selected strategy.", group="linear"),
    field("linearMaxIteration", "Max iterations", "int", default=200, visible_when={"field": "linearSolver", "one_of": ["cg", "bicgstab"]}, group="linear", min=1),
    field("linearTolerance", "Tolerance", "number", default=1e-7, visible_when={"field": "linearSolver", "one_of": ["cg", "bicgstab"]}, group="linear", min=0),
    field("preconditioner", "Preconditioner", "enum", default="none", options=["none", "diagonal", "ilu", "ilu0"], visible_when={"field": "linearSolver", "one_of": ["cg", "bicgstab"]}, group="linear"),
    field("echoLevel", "Echo level", "int", default=1, min=0, max=3, advanced=True),
    field("computeReactions", "Compute reactions", "bool", default=False, advanced=True),
    groups=[field_group("analysis", "Analysis", icon="ptSolver"), field_group("time", "Time", icon="ptTime"), field_group("nonlinear", "Non-linear iteration", icon="ptSolver"), field_group("linear", "Linear solver", icon="ptSolver", collapsed=True)])

CONDITIONS = [
    condition("parts", "Thermal body", list="list_other_processes", target="volume",
              fields=[],
              process_template={

              },
              help="Marks a SubModelPart as computing domain; assign a material to it."),
    condition("initialTemperature", "Initial temperature", list="initial_conditions_process_list", target="any",
              fields=[field("value", "Value [K]", "number", default=293.15),
                      field("constrained", "Fixed", "bool", default=False)],
              process_template={
                  "python_module": "assign_scalar_variable_process",
                  "kratos_module": "KratosMultiphysics",
                  "process_name": "AssignScalarVariableProcess",
                  "Parameters": {
                      "model_part_name": "$path",
                      "variable_name": "TEMPERATURE",
                      "interval": [0, 0],
                      "constrained": "$field:constrained",
                      "value": "$field:value",
                  },
              },
              category="initial", icon="ptInitial"),
    condition("temperature", "Fixed temperature", list="constraints_process_list", target="any",
              fields=[field("value", "Temperature [K]", "number", default=293.15)],
              process_template={
                  "python_module": "assign_scalar_variable_process",
                  "kratos_module": "KratosMultiphysics",
                  "process_name": "AssignScalarVariableProcess",
                  "Parameters": {
                      "model_part_name": "$path",
                      "variable_name": "TEMPERATURE",
                      "constrained": True,
                      "value": "$field:value",
                      "interval": [0, "End"],
                  },
              },
              category="constraints", icon="ptConstraint"),
    condition("heatFlux", "Heat flux (volume)", list="constraints_process_list", target="volume",
              fields=[field("value", "Heat flux [W/m³]", "number", default=0)],
              process_template={
                  "python_module": "assign_scalar_variable_process",
                  "kratos_module": "KratosMultiphysics",
                  "process_name": "AssignScalarVariableProcess",
                  "Parameters": {
                      "model_part_name": "$path",
                      "variable_name": "HEAT_FLUX",
                      "constrained": False,
                      "value": "$field:value",
                      "interval": [0, "End"],
                  },
              },
              category="loads", icon="ptLoad"),
    condition("faceHeatFlux", "Face heat flux", list="constraints_process_list", target="surface",
              fields=[field("value", "Value [W/m²]", "number", default=0)],
              process_template={
                  "python_module": "assign_scalar_variable_to_conditions_process",
                  "kratos_module": "KratosMultiphysics",
                  "process_name": "AssignScalarVariableToConditionsProcess",
                  "Parameters": {
                      "model_part_name": "$path",
                      "variable_name": "FACE_HEAT_FLUX",
                      "value": "$field:value",
                      "interval": [0, "End"],
                  },
              },
              category="loads", icon="ptLoad"),
    condition("thermalFace", "Thermal face (radiation / convection)", list="constraints_process_list", target="surface",
              fields=[field("ambientTemperature", "Ambient temperature [K]", "number", default=273.15),
                      field("addRadiation", "Add ambient radiation", "bool", default=False),
                      field("emissivity", "Emissivity", "number", default=0, visible_when={"field": "addRadiation", "equals": True}, min=0, max=1),
                      field("addConvection", "Add ambient convection", "bool", default=False),
                      field("convectionCoefficient", "Convection coefficient [W/(m²·K)]", "number", default=0, visible_when={"field": "addConvection", "equals": True}, min=0)],
              process_template={
                  "python_module": "apply_thermal_face_process",
                  "kratos_module": "KratosMultiphysics.ConvectionDiffusionApplication",
                  "process_name": "ApplyThermalFaceProcess",
                  "Parameters": {
                      "model_part_name": "$path",
                      "ambient_temperature": "$field:ambientTemperature",
                      "add_ambient_radiation": "$field:addRadiation",
                      "emissivity": "$field:emissivity",
                      "add_ambient_convection": "$field:addConvection",
                      "convection_coefficient": "$field:convectionCoefficient",
                  },
              },
              help="Exchange with the ambient on a boundary: radiation and/or convection.", category="loads", icon="ptLoad"),
]

MATERIAL_LAWS = [
    material_law("thermal", "",
                 variables=[field("DENSITY", "Density [kg/m³]", "number", default=1000, unit="kg/m³"),
                            field("CONDUCTIVITY", "Conductivity [W/(m·K)]", "number", default=0.6, unit="W/(m·K)"),
                            field("SPECIFIC_HEAT", "Specific heat [J/(kg·K)]", "number", default=4184, unit="J/(kg·K)")]),
]



define_problemtype(
    id="convectionDiffusion_py",
    name=NAME,
    sections=[SECTION_0],
    conditions=CONDITIONS,
    material_laws=MATERIAL_LAWS,
    solver_settings=solver_settings,
    description="Transient / stationary heat transfer (ConvectionDiffusionApplication)",
    icon="ptThermal",
    family="thermal",
    analysis_stage="KratosMultiphysics.ConvectionDiffusionApplication.convection_diffusion_analysis",
    model_part_name="ThermalModelPart",
    materials_file_name="ConvectionDiffusionMaterials.json",
    domain_sizes=[2, 3],
    parts_condition="parts",
    mesh_naming={
        "elements": "Element",
        "conditions": {
            "2": "LineCondition",
            "3": "SurfaceCondition",
        },
    },
    output={
        "nodal_defaults": ["TEMPERATURE"],
    },
)
