"""Potential Flow problemtype — Python port of the built-in.

A faithful port of src/problemtype/builtins/potentialFlow.ts, kept as a worked
example of the Python authoring API (parity-tested against the TypeScript
original). The declaration is generated from the TypeScript original by
scripts/problemtype-to-python.mjs; only the hook is hand-written. Notable: no
material laws at all — the free-stream state rides on the far-field process —
and generic mesh names (the solver replaces elements per
formulation.element_type).
"""

from kratos_problemtype import (define_problemtype, section, field, field_group,
                                condition)

NAME = "Potential Flow (Python example)"


def _resolve(node, assignment, ctx):
    """Replaces the $path / $root / $field:<id> placeholders of a template."""
    if isinstance(node, str):
        if node == "$path":
            return ctx["model_part_name"] + "." + assignment["smpPath"].replace("/", ".")
        if node == "$root":
            return ctx["model_part_name"]
        if node.startswith("$field:"):
            return assignment["values"].get(node[len("$field:"):])
        return node
    if isinstance(node, list):
        return [_resolve(item, assignment, ctx) for item in node]
    if isinstance(node, dict):
        return {key: _resolve(item, assignment, ctx) for key, item in node.items()}
    return node


def _broadcast_constrained(cond, assignment, ctx):
    """The single "Fixed" checkbox of an Assign*VariableProcess on nodes becomes
    Kratos' per-component ``constrained: [b, b, b]`` (None for any other condition)."""
    template = cond["processTemplate"]
    if template.get("python_module") != "assign_vector_variable_process":
        return None
    process = _resolve(template, assignment, ctx)
    fixed = assignment["values"].get("constrained", True)
    fixed = fixed if isinstance(fixed, bool) else True
    value = assignment["values"].get("value", [0, 0, 0])
    process["Parameters"]["constrained"] = [fixed, fixed, fixed]
    process["Parameters"]["value"] = value if isinstance(value, list) else [0, 0, 0]
    return process


def _linear_solver(values):
    """``linear_solver_settings`` for the chosen solver (None for Automatic)."""
    solver = values["linearSolver"]
    if solver in ("cg", "bicgstab"):
        return {
            "solver_type": solver,
            "max_iteration": values["linearMaxIteration"],
            "tolerance": values["linearTolerance"],
            "preconditioner_type": values["preconditioner"],
            "scaling": False,
        }
    if solver != "automatic":
        return {"solver_type": solver}
    return None


def solver_settings(values, ctx):
    settings = {
        "model_part_name": ctx["model_part_name"],
        "domain_size": ctx["domain_size"],
        "solver_type": "potential_flow",
        "model_import_settings": {"input_type": "mdpa", "input_filename": ctx["mdpa_stem"]},
        "formulation": {"element_type": values["formulation"]},
        "maximum_iterations": values["maxIterations"],
        "echo_level": values["echoLevel"],
        "volume_model_part_name": (ctx["parts_model_parts"][0]
                                   if ctx["parts_model_parts"] else ctx["model_part_name"]),
        "skin_parts": ctx["skin_model_parts"],
        "no_skin_parts": [],
    }
    linear = _linear_solver(values)
    if linear:
        settings["linear_solver_settings"] = linear
    return settings


# --- declaration of "potentialFlow" generated by scripts/problemtype-to-python.mjs ---
SECTION_0 = section("problem", "Problem data",
    field("formulation", "Formulation", "enum", default="incompressible", options=[{"value": "incompressible", "label": "Incompressible"}, {"value": "compressible", "label": "Compressible"}], group="formulation"),
    field("maxIterations", "Max iterations", "int", default=10, group="convergence", min=1),
    field("linearSolver", "Solver", "enum", default="automatic", options=[{"value": "automatic", "label": "Automatic"}, {"value": "LinearSolversApplication.sparse_lu", "label": "Sparse LU"}, {"value": "cg", "label": "Conjugate gradients"}, {"value": "bicgstab", "label": "BiCGStab"}], help="Automatic lets Kratos pick the default solver of the selected strategy.", group="linear"),
    field("linearMaxIteration", "Max iterations", "int", default=200, visible_when={"field": "linearSolver", "one_of": ["cg", "bicgstab"]}, group="linear", min=1),
    field("linearTolerance", "Tolerance", "number", default=1e-7, visible_when={"field": "linearSolver", "one_of": ["cg", "bicgstab"]}, group="linear", min=0),
    field("preconditioner", "Preconditioner", "enum", default="none", options=["none", "diagonal", "ilu", "ilu0"], visible_when={"field": "linearSolver", "one_of": ["cg", "bicgstab"]}, group="linear"),
    field("echoLevel", "Echo level", "int", default=0, min=0, max=3, advanced=True),
    groups=[field_group("formulation", "Formulation", icon="ptSolver"), field_group("convergence", "Convergence", icon="ptSolver"), field_group("linear", "Linear solver", icon="ptSolver", collapsed=True)])

CONDITIONS = [
    condition("parts", "Fluid domain", list="list_other_processes", target="volume",
              fields=[],
              process_template={

              },
              help="Marks a SubModelPart as the flow domain."),
    condition("farField", "Far field", list="constraints_process_list", target="surface",
              fields=[field("angleOfAttack", "Angle of attack [rad]", "number", default=0),
                      field("machInfinity", "Mach ∞", "number", default=0.03),
                      field("speedOfSound", "Speed of sound [m/s]", "number", default=340)],
              process_template={
                  "python_module": "apply_far_field_and_wake_process",
                  "kratos_module": "KratosMultiphysics.CompressiblePotentialFlowApplication",
                  "process_name": "ApplyFarFieldAndWakeProcess",
                  "Parameters": {
                      "model_part_name": "$path",
                      "angle_of_attack": "$field:angleOfAttack",
                      "mach_infinity": "$field:machInfinity",
                      "speed_of_sound": "$field:speedOfSound",
                  },
              },
              category="constraints", icon="ptConstraint"),
    condition("body2d", "Body / wake (2D)", list="list_other_processes", target="surface",
              fields=[field("epsilon", "Wake ε", "number", default=1e-9)],
              process_template={
                  "python_module": "define_wake_process_2d",
                  "kratos_module": "KratosMultiphysics.CompressiblePotentialFlowApplication",
                  "process_name": "DefineWakeProcess2D",
                  "Parameters": {
                      "model_part_name": "$path",
                      "epsilon": "$field:epsilon",
                  },
              },
              help="The body boundary whose trailing edge sheds the wake (2D cases).", category="other", icon="ptSolver"),
]

MATERIAL_LAWS = [
]



define_problemtype(
    id="potentialFlow_py",
    name=NAME,
    sections=[SECTION_0],
    conditions=CONDITIONS,
    material_laws=MATERIAL_LAWS,
    solver_settings=solver_settings,
    description="Incompressible / compressible potential flow around bodies (CompressiblePotentialFlowApplication)",
    icon="ptPotentialFlow",
    family="fluid",
    analysis_stage="KratosMultiphysics.CompressiblePotentialFlowApplication.potential_flow_analysis",
    model_part_name="FluidModelPart",
    materials_file_name="FluidMaterials.json",
    domain_sizes=[2, 3],
    parts_condition="parts",
    mesh_naming={
        "elements": "Element",
        "conditions": {
            "2": "LineCondition",
            "3": "SurfaceCondition",
        },
    },
    output={
        "nodal_defaults": ["VELOCITY_POTENTIAL", "AUXILIARY_VELOCITY_POTENTIAL"],
    },
)
