"""Shallow Water problemtype — Python port of the built-in.

A faithful port of src/problemtype/builtins/shallowWater.ts, kept as a worked
example of the Python authoring API (parity-tested against the TypeScript
original). The declaration is generated from the TypeScript original by
scripts/problemtype-to-python.mjs; only the hook is hand-written. Notable:
2D-only, MANNING-roughness materials without a constitutive law, and the app's
own process lists (topography / initial_conditions / boundary_conditions)
instead of the GiD-standard three.
"""

from kratos_problemtype import (define_problemtype, section, field, field_group,
                                condition, material_law)

NAME = "Shallow Water (Python example)"


def _resolve(node, assignment, ctx):
    """Replaces the $path / $root / $field:<id> placeholders of a template."""
    if isinstance(node, str):
        if node == "$path":
            return ctx["model_part_name"] + "." + assignment["smpPath"].replace("/", ".")
        if node == "$root":
            return ctx["model_part_name"]
        if node.startswith("$field:"):
            return assignment["values"].get(node[len("$field:"):])
        return node
    if isinstance(node, list):
        return [_resolve(item, assignment, ctx) for item in node]
    if isinstance(node, dict):
        return {key: _resolve(item, assignment, ctx) for key, item in node.items()}
    return node


def _broadcast_constrained(cond, assignment, ctx):
    """The single "Fixed" checkbox of an Assign*VariableProcess on nodes becomes
    Kratos' per-component ``constrained: [b, b, b]`` (None for any other condition)."""
    template = cond["processTemplate"]
    if template.get("python_module") != "assign_vector_variable_process":
        return None
    process = _resolve(template, assignment, ctx)
    fixed = assignment["values"].get("constrained", True)
    fixed = fixed if isinstance(fixed, bool) else True
    value = assignment["values"].get("value", [0, 0, 0])
    process["Parameters"]["constrained"] = [fixed, fixed, fixed]
    process["Parameters"]["value"] = value if isinstance(value, list) else [0, 0, 0]
    return process


def _linear_solver(values):
    """``linear_solver_settings`` for the chosen solver (None for Automatic)."""
    solver = values["linearSolver"]
    if solver in ("cg", "bicgstab"):
        return {
            "solver_type": solver,
            "max_iteration": values["linearMaxIteration"],
            "tolerance": values["linearTolerance"],
            "preconditioner_type": values["preconditioner"],
            "scaling": False,
        }
    if solver != "automatic":
        return {"solver_type": solver}
    return None


def solver_settings(values, ctx):
    solver = values["solver"]
    scheme = values["scheme"]
    settings = {
        "solver_type": solver,
        "model_part_name": ctx["model_part_name"],
        "domain_size": 2,
        "gravity": values["gravity"],
        "model_import_settings": {"input_type": "mdpa", "input_filename": ctx["mdpa_stem"]},
        "material_import_settings": {"materials_filename": ctx["materials_file_name"]},
        "echo_level": values["echoLevel"],
        "maximum_iterations": values["maxIterations"],
        "stabilization_factor": values["stabilizationFactor"],
    }
    if solver == "stabilized_shallow_water_solver":
        settings["shock_capturing_type"] = values["shockCapturing"]
    if solver != "wave_solver":
        settings["shock_capturing_factor"] = values["shockCapturingFactor"]
    # The scheme's own parameter, written flat like GiD does.
    if scheme in ("bdf", "Adams-Moulton"):
        settings["time_integration_order"] = values["timeIntegrationOrder"]
    linear = _linear_solver(values)
    if linear:
        settings["linear_solver_settings"] = linear
    if values["adaptiveStep"]:
        settings["time_stepping"] = {
            "automatic_time_step": True,
            "courant_number": values["cflNumber"],
            "maximum_delta_time": values["maxDeltaTime"],
            "minimum_delta_time": values["minDeltaTime"],
        }
    else:
        settings["time_stepping"] = {"automatic_time_step": False, "time_step": values["timeStep"]}
    return settings


# --- declaration of "shallowWater" generated by scripts/problemtype-to-python.mjs ---
SECTION_0 = section("problem", "Problem data",
    field("solver", "Solution type", "enum", default="stabilized_shallow_water_solver", options=[{"value": "stabilized_shallow_water_solver", "label": "Shallow water flow"}, {"value": "boussinesq_solver", "label": "Dispersive waves (Boussinesq)"}, {"value": "wave_solver", "label": "Linear waves"}], group="model"),
    field("scheme", "Scheme", "enum", default="bdf", options=[{"value": "bdf", "label": "BDF"}, {"value": "Adams-Moulton", "label": "Adams-Moulton"}, {"value": "cn", "label": "Crank-Nicolson"}], help="Adams-Moulton belongs to the Boussinesq solver and Crank-Nicolson to the linear-wave solver.", group="model"),
    field("timeIntegrationOrder", "Integration order", "int", default=2, visible_when={"field": "scheme", "one_of": ["bdf", "Adams-Moulton"]}, group="model", min=1, max=4),
    field("startTime", "Start time", "number", default=0, unit="s", group="time"),
    field("endTime", "End time", "number", default=1, unit="s", group="time"),
    field("adaptiveStep", "Automatic time step (CFL)", "bool", default=False, group="time"),
    field("timeStep", "Time step", "number", default=0.01, visible_when={"field": "adaptiveStep", "equals": False}, unit="s", group="time", min=0),
    field("cflNumber", "CFL number", "number", default=1, visible_when={"field": "adaptiveStep", "equals": True}, group="time", min=0),
    field("minDeltaTime", "Min. time step", "number", default=0.0001, visible_when={"field": "adaptiveStep", "equals": True}, group="time"),
    field("maxDeltaTime", "Max. time step", "number", default=1, visible_when={"field": "adaptiveStep", "equals": True}, group="time"),
    field("maxIterations", "Max iterations", "int", default=10, group="stabilization", min=1),
    field("stabilizationFactor", "Stabilization factor", "number", default=0.01, group="stabilization", min=0),
    field("shockCapturing", "Shock capturing", "enum", default="residual_viscosity", options=[{"value": "residual_viscosity", "label": "Residual viscosity"}, {"value": "gradient_jump", "label": "Gradient jump"}, {"value": "flux_correction", "label": "Flux correction"}], visible_when={"field": "solver", "equals": "stabilized_shallow_water_solver"}, group="stabilization"),
    field("shockCapturingFactor", "Shock capturing factor", "number", default=0.5, visible_when={"field": "solver", "one_of": ["stabilized_shallow_water_solver", "boussinesq_solver"]}, group="stabilization", min=0),
    field("gravity", "Gravity", "number", default=9.81, unit="m/s²", help="Always vertical, positive down.", group="gravity"),
    field("linearSolver", "Solver", "enum", default="automatic", options=[{"value": "automatic", "label": "Automatic"}, {"value": "LinearSolversApplication.sparse_lu", "label": "Sparse LU"}, {"value": "cg", "label": "Conjugate gradients"}, {"value": "bicgstab", "label": "BiCGStab"}], help="Automatic lets Kratos pick the default solver of the selected strategy.", group="linear"),
    field("linearMaxIteration", "Max iterations", "int", default=200, visible_when={"field": "linearSolver", "one_of": ["cg", "bicgstab"]}, group="linear", min=1),
    field("linearTolerance", "Tolerance", "number", default=1e-7, visible_when={"field": "linearSolver", "one_of": ["cg", "bicgstab"]}, group="linear", min=0),
    field("preconditioner", "Preconditioner", "enum", default="none", options=["none", "diagonal", "ilu", "ilu0"], visible_when={"field": "linearSolver", "one_of": ["cg", "bicgstab"]}, group="linear"),
    field("echoLevel", "Echo level", "int", default=1, min=0, max=3, advanced=True),
    groups=[field_group("model", "Physics", icon="ptSolver"), field_group("time", "Time", icon="ptTime"), field_group("stabilization", "Stabilization", icon="ptSolver"), field_group("gravity", "Gravity", icon="ptGravity"), field_group("linear", "Linear solver", icon="ptSolver", collapsed=True)])

CONDITIONS = [
    condition("parts", "Water domain", list="list_other_processes", target="volume",
              fields=[],
              process_template={

              },
              help="Marks a SubModelPart as computing domain; assign a Manning roughness to it."),
    condition("initialWaterLevel", "Initial water level", list="initial_conditions_process_list", target="volume",
              fields=[field("variable", "Variable", "enum", default="HEIGHT", options=["HEIGHT", "FREE_SURFACE_ELEVATION"]),
                      field("value", "Value [m]", "number", default=1),
                      field("setMinimumHeight", "Set a minimum height", "bool", default=False),
                      field("minimumHeight", "Minimum height [m]", "number", default=0.001, visible_when={"field": "setMinimumHeight", "equals": True}, min=0)],
              process_template={
                  "python_module": "set_initial_water_level_process",
                  "kratos_module": "KratosMultiphysics.ShallowWaterApplication",
                  "process_name": "SetInitialWaterLevelProcess",
                  "Parameters": {
                      "model_part_name": "$path",
                      "variable_name": "$field:variable",
                      "value": "$field:value",
                      "set_minimum_height": "$field:setMinimumHeight",
                      "minimum_height_value": "$field:minimumHeight",
                  },
              },
              category="initial", icon="ptInitial"),
    condition("initialPerturbation", "Initial perturbation", list="initial_conditions_process_list", target="volume",
              fields=[field("variable", "Variable", "enum", default="HEIGHT", options=["HEIGHT", "FREE_SURFACE_ELEVATION"]),
                      field("maximumPerturbation", "Maximum value [m]", "number", default=1),
                      field("distanceOfInfluence", "Distance of influence [m]", "number", default=1, min=0),
                      field("defaultValue", "Default value [m]", "number", default=0),
                      field("sourceCoordinates", "Source point", "vector3", default=[0, 0, 0])],
              process_template={
                  "python_module": "set_initial_perturbation_process",
                  "kratos_module": "KratosMultiphysics.ShallowWaterApplication",
                  "process_name": "SetInitialPerturbationProcess",
                  "Parameters": {
                      "model_part_name": "$path",
                      "variable_name": "$field:variable",
                      "maximum_perturbation_value": "$field:maximumPerturbation",
                      "distance_of_influence": "$field:distanceOfInfluence",
                      "default_value": "$field:defaultValue",
                      "source_type": "coordinates",
                      "source_coordinates": "$field:sourceCoordinates",
                  },
              },
              help="A localised bump on the initial water level, centred on given coordinates.", category="initial", icon="ptInitial"),
    condition("imposedFlowRate", "Imposed flow rate", list="boundary_conditions_process_list", target="surface",
              fields=[field("value", "q [m²/s]", "vector3", default=[0, 0, 0])],
              process_template={
                  "python_module": "assign_vector_variable_process",
                  "kratos_module": "KratosMultiphysics",
                  "process_name": "AssignVectorVariableProcess",
                  "Parameters": {
                      "model_part_name": "$path",
                      "variable_name": "MOMENTUM",
                      "value": "$field:value",
                      "interval": [0, "End"],
                  },
              },
              category="constraints", icon="ptConstraint"),
    condition("imposedVelocity", "Imposed velocity", list="boundary_conditions_process_list", target="surface",
              fields=[field("value", "v [m/s]", "vector3", default=[0, 0, 0])],
              process_template={
                  "python_module": "assign_vector_variable_process",
                  "kratos_module": "KratosMultiphysics",
                  "process_name": "AssignVectorVariableProcess",
                  "Parameters": {
                      "model_part_name": "$path",
                      "variable_name": "VELOCITY",
                      "value": "$field:value",
                      "interval": [0, "End"],
                  },
              },
              category="constraints", icon="ptConstraint"),
    condition("imposedFreeSurface", "Imposed free surface", list="boundary_conditions_process_list", target="surface",
              fields=[field("value", "Elevation [m]", "number", default=0)],
              process_template={
                  "python_module": "assign_scalar_variable_process",
                  "kratos_module": "KratosMultiphysics",
                  "process_name": "AssignScalarVariableProcess",
                  "Parameters": {
                      "model_part_name": "$path",
                      "variable_name": "HEIGHT",
                      "value": "$field:value",
                      "interval": [0, "End"],
                  },
              },
              category="constraints", icon="ptConstraint"),
    condition("slip", "Slip wall", list="boundary_conditions_process_list", target="surface",
              fields=[],
              process_template={
                  "python_module": "apply_slip_process",
                  "kratos_module": "KratosMultiphysics.ShallowWaterApplication",
                  "process_name": "ApplySlipProcess",
                  "Parameters": {
                      "model_part_name": "$path",
                  },
              },
              category="constraints", icon="ptConstraint"),
    condition("topography", "Topography", list="topography_process_list", target="volume",
              fields=[field("value", "z(x,y) expression", "string", default="0.0", help="Bathymetry as a function of x and y, e.g. 0.05*x")],
              process_template={
                  "python_module": "set_topography_process",
                  "kratos_module": "KratosMultiphysics.ShallowWaterApplication",
                  "process_name": "SetTopographyProcess",
                  "Parameters": {
                      "model_part_name": "$path",
                      "value": "$field:value",
                  },
              },
              category="other", icon="ptParts"),
]

MATERIAL_LAWS = [
    material_law("manning", "",
                 variables=[field("MANNING", "Manning coefficient", "number", default=0.01)]),
]



define_problemtype(
    id="shallowWater_py",
    name=NAME,
    sections=[SECTION_0],
    conditions=CONDITIONS,
    material_laws=MATERIAL_LAWS,
    solver_settings=solver_settings,
    description="2D free-surface shallow-water flows: stabilized, Boussinesq and linear waves (ShallowWaterApplication)",
    icon="ptShallowWater",
    family="fluid",
    analysis_stage="KratosMultiphysics.ShallowWaterApplication.shallow_water_analysis",
    model_part_name="main_model_part",
    materials_file_name="TopographyMaterials.json",
    domain_sizes=[2],
    parts_condition="parts",
    mesh_naming={
        "elements": "Element",
        "conditions": {
            "2": "LineCondition",
        },
    },
    output={
        "nodal_defaults": ["HEIGHT", "MOMENTUM", "VELOCITY"],
    },
)
