// GENERATED by scripts/gen-export-fidelity.js — do not edit by hand.
// One entry per writer key (native writers by extension), measured by writing
// the reference model of src/test/exportReportMatrix.ts and re-reading it.
// Codes: r = retained, t = transformed, o = omitted. `fields` is keyed
// "<kind>:<components>". `unmeasured` names why the reference mesh could not
// be round-tripped, and the report then says "unverified" instead of guessing.
// exportReport.test.ts fails when this file stops matching a fresh measurement.

export type Code = "r" | "t" | "o";

export interface MeasuredRow {
  base: Partial<Record<string, Code>>;
  fields: Record<string, Code>;
}

export type MeasuredEntry = MeasuredRow | { unmeasured: string };

/** VTK cell types the reference mesh contains (hexahedron, quad); claims about other types are unverified. */
export const MEASURED_CELL_TYPES: readonly number[] = [9, 12];

export const EXPORT_FIDELITY_TABLE: Readonly<Record<string, MeasuredEntry>> = {
  ".mdpa": {"base":{"nodes":"r","nodeIds":"r","connectivity":"r","entityIds":"r","blocks":"r","properties":"r","constraints":"r","subModelParts":"r","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"r"}},
  ".obj": {"base":{"nodes":"r","nodeIds":"t","connectivity":"t","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  ".ply": {"base":{"nodes":"r","nodeIds":"t","connectivity":"t","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"o","Elemental:1":"o"}},
  ".stl": {"base":{"nodes":"t","nodeIds":"t","connectivity":"t","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  ".vtk": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"t"}},
  ".vtm": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"t"}},
  ".vtp": {"base":{"nodes":"r","nodeIds":"t","connectivity":"t","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"o"}},
  ".vtu": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"t"}},
  "abaqus": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "ansys": {"base":{"nodes":"r","nodeIds":"t","connectivity":"t","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "ansysinp": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "avsucd": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"t"}},
  "cgns": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"o"}},
  "code_aster": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "dex": {"base":{"nodes":"r","nodeIds":"t","connectivity":"o","entityIds":"o","blocks":"o","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"r","Elemental:1":"o"}},
  "dolfin": {"unmeasured":"DOLFIN XML only supports triangles and tetrahedra"},
  "elmer": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "ensight": {"unmeasured":"Could not read \"out.case\" as ensight: ensight: EnSight: could not open variable file: /mio_in/DISPLACEMENT.vec"},
  "exodus": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"r"}},
  "febio": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"r"}},
  "femap": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"o","Elemental:1":"t"}},
  "flac3d": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "flux": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "freefem": {"unmeasured":"FreeFem: unsupported cell type hexahedron"},
  "gid": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"t"}},
  "gmsh": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"t"}},
  "h5m": {"base":{"nodes":"r","nodeIds":"t","connectivity":"o","entityIds":"o","blocks":"o","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"o"}},
  "hmf": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"t"}},
  "ip": {"base":{"nodes":"r","nodeIds":"t","connectivity":"o","entityIds":"o","blocks":"o","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"o","Elemental:1":"o"}},
  "libmesh": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "lsdyna": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "med": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"t"}},
  "medit": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "mfem": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "mff": {"base":{"nodes":"o","nodeIds":"o","connectivity":"o","entityIds":"o","blocks":"o","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "mfm": {"unmeasured":"MFM can only write a single element type"},
  "mphbin": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "mphtxt": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "nastran": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "netgen": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "off": {"base":{"nodes":"r","nodeIds":"t","connectivity":"t","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "openfoam": {"base":{"nodes":"r","nodeIds":"t","connectivity":"t","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"r"}},
  "patran": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "pcd": {"base":{"nodes":"r","nodeIds":"t","connectivity":"t","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"o"}},
  "permas": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "su2": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "svg": {"unmeasured":"write-only format: this extension has no reader to check the output against"},
  "tecplot": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"o","Elemental:1":"t"}},
  "tetgen": {"unmeasured":"Could not read \"out.ele\" as tetgen: tetgen: TetGen: missing header line in /mio_in/out.ele"},
  "tikz": {"unmeasured":"write-only format: this extension has no reader to check the output against"},
  "triangle": {"unmeasured":"Triangle: can only write 2D points"},
  "ugrid": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "unv": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"t"}},
  "vtkhdf": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"t"}},
  "wkt": {"base":{"nodes":"o","nodeIds":"o","connectivity":"o","entityIds":"o","blocks":"o","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
  "xdmf": {"base":{"nodes":"r","nodeIds":"t","connectivity":"r","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"r","Elemental:1":"t"}},
  "xyz": {"base":{"nodes":"r","nodeIds":"t","connectivity":"t","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"o","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"r","Nodal:3":"o","Elemental:1":"o"}},
  "z88": {"base":{"nodes":"r","nodeIds":"t","connectivity":"t","entityIds":"t","blocks":"t","properties":"o","constraints":"o","subModelParts":"t","fieldDimensions":"o","globals":"o","source":"o"},"fields":{"Nodal:1":"o","Nodal:3":"o","Elemental:1":"o"}},
};
