/** Pure skeleton shared by the packaged webview and its CSP/export regression. */
import { glyph } from "../../uiGlyphs";
export const PLOT_PANE_HTML = `<button type="button" id="plot-restore" class="hidden panel-btn">${glyph("chartLine")} Plots</button>
<div id="plot-resizer" class="hidden" role="separator" aria-label="Resize mesh and plot panes" aria-orientation="vertical" aria-valuemin="20" aria-valuemax="75" aria-valuenow="48" tabindex="0"></div>
<section id="plot-pane" class="hidden" aria-label="FEM postprocessing">
  <div id="plot-pane-header"><span class="panel-title">${glyph("chartLine")} Plots <span class="plot-muted">· FEM postprocessing</span></span><span class="plot-pane-controls"><button type="button" id="plot-orient" class="panel-btn" title="Dock below or beside the mesh">${glyph("panelLeft")} <span>Dock below</span></button><button type="button" id="plot-hide" class="panel-btn" aria-label="Collapse plots" title="Collapse plots">${glyph("chevronRight")}</button></span></div>
  <div id="plot-app" class="plot-embedded"><header><div id="plot-actions"></div></header><div id="plot-quick"></div><div id="plot-curves" aria-label="Plot curves"></div><main><aside id="plot-config" aria-label="Advanced plot configuration"></aside><section id="plot-results" aria-label="Plot preview"><div id="plot-chart-tools"></div><div id="plot-status" role="status" aria-live="polite">Pick a point or choose a SubModelPart.</div><div id="plot-chart" tabindex="0" aria-label="Chart; keyboard-accessible values in the samples table"></div><div id="plot-peaks"></div><div id="plot-coverage" aria-label="Units and coverage"></div><details><summary>Sources, transformations and diagnostics</summary><div id="plot-diagnostics"></div></details><details><summary>Plotted samples</summary><div id="plot-samples"></div></details></section></main></div>
</section>`;
export function plotHtml(script: string, library: string, design: string, style: string, nonce: string, cspSource: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-${nonce}'; style-src ${cspSource} 'unsafe-inline'; img-src data: blob: ${cspSource}; font-src ${cspSource};"><link rel="stylesheet" href="${design}"><link rel="stylesheet" href="${style}"></head><body><div id="plot-app"><header><h1>${glyph("chartLine")} Scientific plots</h1><div id="plot-actions"></div></header><main><aside id="plot-config" aria-label="Plot configuration"></aside><section id="plot-results" aria-label="Plot preview"><div id="plot-chart-tools"></div><div id="plot-status" role="status" aria-live="polite">Choose a source to begin.</div><div id="plot-chart" tabindex="0" aria-label="Chart; use the sample table for keyboard-accessible values"></div><div id="plot-curves" aria-label="Plot curves"></div><details><summary>Sources, transformations and diagnostics</summary><div id="plot-diagnostics"></div></details><details><summary>Plotted samples — keyboard-accessible table</summary><div id="plot-samples"></div></details></section></main></div><script nonce="${nonce}" src="${library}"></script><script nonce="${nonce}" src="${script}"></script></body></html>`;
}
