#!/usr/bin/env node
// Regenerate src/parser/render/vtkWasmGlueNeedles.ts from the pinned glue
// (roadmap item 18, Phase 1). Run after `fetch.mjs`, and ONLY as part of a
// deliberate re-pin: the needles are what patchGlue matches byte for byte,
// so regenerating them is the moment to re-review the replacement semantics
// in vtkWasmGlue.ts against the new upstream text and re-run the
// differential test (src/test/vtkWasmGlue.test.ts).
//
//   node scripts/vtk-wasm/extract-needles.mjs
//
// The sync needle comes from the rel-9.7.0 SYNC build and the async one from
// the unified latest build; the emval needle must be identical in both, and
// every needle must occur exactly once in its source — anything else aborts.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const OUT = join(ROOT, "src", "parser", "render", "vtkWasmGlueNeedles.ts");

/** Extract a function by brace matching from its signature prefix. */
function grab(src, start) {
  const i = src.indexOf(start);
  if (i < 0) throw new Error(`not found: ${start}`);
  let d = 0;
  for (let k = src.indexOf("{", i); k < src.length; k++) {
    if (src[k] === "{") d++;
    else if (src[k] === "}" && --d === 0) return src.slice(i, k + 1);
  }
  throw new Error(`unbalanced: ${start}`);
}

const count = (s, n) => s.split(n).length - 1;
const syncSrc = readFileSync(join(ROOT, "out/vtk-wasm/rel-9.7.0/vtkWebAssembly.mjs"), "latin1");
const asyncSrc = readFileSync(join(ROOT, "out/vtk-wasm/latest-9.7.20260920/vtkWebAssembly.mjs"), "latin1");

const sync = grab(syncSrc, "function createJsInvoker(");
const asyncV = grab(asyncSrc, "function createJsInvoker(");
const emval = grab(syncSrc, "var __emval_create_invoker=function(");
const anchor = 'Module["specialHTMLTargets"]=specialHTMLTargets;';

if (grab(asyncSrc, "var __emval_create_invoker=function(") !== emval) throw new Error("emval invoker differs between builds");
for (const [label, src, needle] of [
  ["sync createJsInvoker", syncSrc, sync],
  ["async createJsInvoker", asyncSrc, asyncV],
  ["emval (sync)", syncSrc, emval],
  ["emval (async)", asyncSrc, emval],
  ["anchor (sync)", syncSrc, anchor],
  ["anchor (async)", asyncSrc, anchor],
]) {
  const n = count(src, needle);
  if (n !== 1) throw new Error(`${label}: ${n} occurrences, expected exactly 1`);
}

const header = `// GENERATED by scripts/vtk-wasm/extract-needles.mjs from the pinned VTK-wasm glue
// (scripts/vtk-wasm/manifest.json). Do not hand-edit: these are the EXACT upstream
// Emscripten embind source texts that vtkWasmGlue.ts replaces, byte for byte. A
// re-pin whose glue differs anywhere inside these functions must fail patchGlue
// loudly rather than be patched on a guess — regenerate, re-review the
// replacement semantics, and re-run the differential test.
//
// Upstream: emscripten src/lib/libembind.js (MIT/University of Illinois NCSA).

`;
writeFileSync(
  OUT,
  header +
    `/** \`createJsInvoker\` as emitted into the SYNC build (no onDone/isAsync tail). */\nexport const NEEDLE_CREATE_JS_INVOKER_SYNC =\n  ${JSON.stringify(sync)};\n\n` +
    `/** \`createJsInvoker\` as emitted into the JSPI/async and unified builds. */\nexport const NEEDLE_CREATE_JS_INVOKER_ASYNC =\n  ${JSON.stringify(asyncV)};\n\n` +
    `/** \`__emval_create_invoker\` (identical in every pinned build). */\nexport const NEEDLE_EMVAL_CREATE_INVOKER =\n  ${JSON.stringify(emval)};\n\n` +
    `/** Anchor after which the heap-export getters are inserted (builds that do not export HEAPU8). */\nexport const NEEDLE_EXPORTS_ANCHOR = ${JSON.stringify(anchor)};\n`
);
console.log(`wrote ${OUT}`);
