#!/usr/bin/env node
// Prepare the VTK-wasm renderer runtime for packaging (roadmap item 18, Phase 3).
//
//   npm run vtkwasm:prepare            # = node scripts/vtk-wasm/prepare-assets.mjs
//
// One step, every gate on the way:
//   1. fetch (cache first, then by COMMIT) and hash-verify the selected
//      candidate from scripts/vtk-wasm/manifest.json, file by file;
//   2. patch the glue (src/parser/render/vtkWasmGlue.ts) and verify the output
//      hash recorded in the manifest — no 'unsafe-eval' needed at runtime;
//   3. audit the backend's declared API usage (vtkWasmApiUsage.ts) against the
//      build's own method table: a missing or unexpectedly-suspending method
//      fails the BUILD, since the session answers a bad call with a logged
//      null, never an exception;
//   4. stage the licences collected by collect-licenses.mjs (committed);
//   5. write out/vtk-wasm/prepared/ with a provenance manifest of every file.
//
// esbuild.js copies out/vtk-wasm/prepared/ into media/vtk-wasm/ (the webview's
// only resource root), re-verifying each hash, and calls this script itself
// for a production build when the prepared tree is missing.

import { copyFileSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { processCandidate, readManifest, sha256 } from "./fetch.mjs";
import { patchCandidate } from "./patch-glue.mjs";
import { auditUsage } from "./audit-usage.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
export const PREPARED_DIR = join(ROOT, "out", "vtk-wasm", "prepared");
export const PREPARED_MANIFEST = "vtk-wasm-assets.json";

/** Files a prepared tree must contain (beside its own manifest). */
export const PREPARED_FILES = ["vtkWebAssembly.mjs", "vtkWebAssembly.wasm", "LICENSE.vtk.txt", "THIRD_PARTY_NOTICES.md"];

export async function prepareAssets({ log = console.log } = {}) {
  const m = readManifest();
  const name = m.selected;
  const spec = m.candidates[name];
  if (!spec) throw new Error(`manifest.selected "${name}" is not a candidate`);

  await processCandidate(m, name, { record: false, verifyOnly: false, noCache: false });

  rmSync(PREPARED_DIR, { recursive: true, force: true });
  mkdirSync(PREPARED_DIR, { recursive: true });
  const patched = await patchCandidate({ candidate: name, outDir: PREPARED_DIR });

  const audit = await auditUsage(name);
  if (audit.problems.length) {
    throw new Error(
      `VTK-wasm API audit failed for ${name}:\n  ` + audit.problems.map((p) => `${p.problem}: ${p.entry.cls}::${p.entry.method}`).join("\n  ")
    );
  }

  for (const f of ["LICENSE.vtk.txt", "THIRD_PARTY_NOTICES.md"]) copyFileSync(join(HERE, "licenses", f), join(PREPARED_DIR, f));

  const files = {};
  for (const f of PREPARED_FILES) {
    const buf = readFileSync(join(PREPARED_DIR, f));
    files[f] = { bytes: buf.length, sha256: sha256(buf) };
  }
  const provenance = {
    _comment: "Provenance of the VTK-wasm renderer runtime shipped in media/vtk-wasm/. Generated by scripts/vtk-wasm/prepare-assets.mjs; do not edit.",
    candidate: name,
    vtkVersion: spec.vtkVersion,
    upstream: `https://github.com/${m.repo}/tree/${m.commit}/${spec.path}`,
    tarballSha256: spec.sha256,
    gluePatches: patched.applied,
    licensesFrom: m.licenses,
    apiUsageEntries: audit.resolved.length,
    files,
  };
  writeFileSync(join(PREPARED_DIR, PREPARED_MANIFEST), JSON.stringify(provenance, null, 2) + "\n");
  const total = Object.values(files).reduce((s, f) => s + f.bytes, 0);
  log(`VTK-wasm ${spec.vtkVersion} prepared -> ${PREPARED_DIR} (${(total / 1048576).toFixed(1)} MB, ${audit.resolved.length} API entries audited)`);
  return provenance;
}

/**
 * Verify a prepared (or copied) tree against its own manifest. Returns the
 * list of problems; empty means every file is present and byte-identical.
 */
export function verifyPrepared(dir) {
  let manifest;
  try {
    manifest = JSON.parse(readFileSync(join(dir, PREPARED_MANIFEST), "utf8"));
  } catch {
    return [`${PREPARED_MANIFEST} missing`];
  }
  const problems = [];
  for (const [f, want] of Object.entries(manifest.files ?? {})) {
    let buf;
    try {
      if (statSync(join(dir, f)).size !== want.bytes) {
        problems.push(`${f}: size`);
        continue;
      }
      buf = readFileSync(join(dir, f));
    } catch {
      problems.push(`${f}: missing`);
      continue;
    }
    if (sha256(buf) !== want.sha256) problems.push(`${f}: sha256`);
  }
  return problems;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  prepareAssets().catch((e) => {
    console.error(e.message || e);
    process.exit(1);
  });
}
